### ISSUE TITLE
html at 4 space indentation treated like markdown code block?

### ISSUE THREAD

**Issue by Strangehill** [tpope/vim-liquid#17]
![screen shot 2017-10-13 at 1 17 14 pm](https://user-images.githubusercontent.com/6064830/31531310-e62c2542-afab-11e7-833c-7ab5d7b28031.png)

**Comment by tpope** [comment]
Check `:echo b:liquid_subtype`.

**Comment by Strangehill** [comment]
It returns 'markdown' (and it is an .md file).

**Comment by Strangehill** [comment]
It seems this is not an issue belonging here but in vim-markdown, and it actually looks like it might be the same issue as this: "Don't apply markdown highlighting in HTML contexts"
 https://github.com/tpope/vim-markdown/issues/11
